name: quick-test
on:
  push:
    branches:
      - main

jobs:
  release:
    name: quick test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
